# Generated by Django 5.0.6 on 2024-06-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='firstName',
            field=models.CharField(null=True),
        ),
    ]
