# Generated by Django 5.0.6 on 2024-07-04 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_command_delete_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Command',
            new_name='Order',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wording', models.CharField()),
                ('price', models.IntegerField()),
                ('stock', models.SmallIntegerField(null=True)),
                ('description', models.TextField()),
                ('picture', models.ImageField(null=True, upload_to='product/')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('products', models.ManyToManyField(null=True, related_name='categories', to='orders.product')),
            ],
        ),
    ]
