# Generated by Django 5.0.6 on 2024-07-04 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='disponibility',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='command',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
